### ISSUE TITLE
ByteXmlWriter outputs extra characters on buffer boundaries

### ISSUE THREAD

**Issue by elDracoRus** [FasterXML/aalto-xml#26]
Specifically method `writeSplitCharacters` outputs additional byte after every `output2ByteChar(ch)` call. There are one line fix for this. Code fragment
```java
case CT_MULTIBYTE_2: // 3, 4 and N can never occur
    // To off-line or not?
    output2ByteChar(ch);
    break;
```
in `writeSplitCharacters` should be changed to
```java
case CT_MULTIBYTE_2: // 3, 4 and N can never occur
    // To off-line or not?
    output2ByteChar(ch);
    continue main_loop;
```
Tell me if pull request is needed for this.

**Comment by cowtowncoder** [comment]
Thank you for reporting this -- wish I had noticed it before I pushed 0.9.10 version.

No PR needed, sounds straight-forward enough.

**Comment by cowtowncoder** [comment]
Took a bit longer to actually write a unit test, but was able to do that, fix the problem.
