### ISSUE TITLE
Would be nice to have a dedicated UTF-16 parser for byte streams

### ISSUE THREAD

**Issue by nick-smith-bbp-ch** [FasterXML/aalto-xml#36]
When creating a parser for UTF-16 byte streams, the XMLInputFactory returns a character stream based parser using java.io.InputStreamReader to bridge the streams.

The Javadoc for `com.fasterxml.aalto.in.ReaderScanner` states : "In general using this scanner is quite a bit less optimal than that of `java.io.InputStream` based scanner".

Additionally a side-effect of not having a dedicated byte-based parser is that the value returned by `javax.xml.stream.Location#getCharacterOffset()` method returns the character offset and not the expected byte offset.

**Comment by cowtowncoder** [comment]
This could be useful. But is UTF-16 used a lot for input? Last statistics I recall seeing had UTF-8 and Latin-1 as dominating, and UTF-16 share was very small.
