### ISSUE TITLE
XMLStreamWriter#writeNamespace writes XMLConstants.XML_NS_URI

### ISSUE THREAD

**Issue by sco0ter** [FasterXML/aalto-xml#37]
I recognized that

```
com.fasterxml.aalto.out.NonRepairingStreamWriter#writeNamespace(XMLConstants.XML_NS_PREFIX, XMLConstants.XML_NS_URI)
```

writes the full namespace `xmlns` declaration, e.g.:

```
<element xmlns:xml="http://www.w3.org/XML/1998/namespace" xml:lang="en">
```

although it's not necessary.

The reference implemention which ships with the JDK behaves differently, it doesn't write the full namespace.

It's not a bug, but the XML looks bloated.

**Comment by cowtowncoder** [comment]
If you do not want that namespace written, why are you calling write method to write it out?
To me the expected behavior is to write the namespace declaration because caller explicitly requested that.

**Comment by sco0ter** [comment]
You are probably right. I was only confused because the reference implementation doesn't write it. Thanks for caring.

**Comment by cowtowncoder** [comment]
@sco0ter also: apologies for super slow follow up :-)
(now going through accumulated issues and trying to address)
