### ISSUE TITLE
Source files without license headers

### ISSUE THREAD

**Issue by puntogil** [FasterXML/aalto-xml#38]
Hi,

The following source files are without license headers:

./src/main/java/com/fasterxml/aalto/AsyncByteArrayFeeder.java
./src/main/java/com/fasterxml/aalto/AsyncByteBufferFeeder.java
./src/main/java/com/fasterxml/aalto/AsyncInputFeeder.java
./src/main/java/com/fasterxml/aalto/AsyncXMLInputFactory.java
./src/main/java/com/fasterxml/aalto/AsyncXMLStreamReader.java
./src/main/java/com/fasterxml/aalto/package-info.java
./src/main/java/com/fasterxml/aalto/ValidationException.java

./src/main/java/com/fasterxml/aalto/async/AsyncByteScanner.java
./src/main/java/com/fasterxml/aalto/async/AsyncStreamReaderImpl.java
./src/main/java/com/fasterxml/aalto/async/package-info.java

./src/main/java/com/fasterxml/aalto/dom/BijectiveNsMap.java
./src/main/java/com/fasterxml/aalto/dom/DOMOutputElement.java
./src/main/java/com/fasterxml/aalto/dom/DOMReaderImpl.java
./src/main/java/com/fasterxml/aalto/dom/DOMWriterImpl.java
./src/main/java/com/fasterxml/aalto/dom/OutputElementBase.java

./src/main/java/com/fasterxml/aalto/evt/IncompleteEvent.java

./src/main/java/com/fasterxml/aalto/impl/CommonConfig.java
./src/main/java/com/fasterxml/aalto/impl/ErrorConsts.java
./src/main/java/com/fasterxml/aalto/impl/IoStreamException.java
./src/main/java/com/fasterxml/aalto/impl/LocationImpl.java

./src/main/java/com/fasterxml/aalto/in/ElementScope.java
./src/main/java/com/fasterxml/aalto/in/FixedNsContext.java
./src/main/java/com/fasterxml/aalto/in/MergedStream.java
./src/main/java/com/fasterxml/aalto/in/PName3.java
./src/main/java/com/fasterxml/aalto/in/ReaderConfig.java
./src/main/java/com/fasterxml/aalto/in/ReaderScanner.java
./src/main/java/com/fasterxml/aalto/in/XmlScanner.java

./src/main/java/com/fasterxml/aalto/io/UTF8Writer.java

./src/main/java/com/fasterxml/aalto/sax/SAXFeature.java
./src/main/java/com/fasterxml/aalto/sax/SAXProperty.java

./src/main/java/com/fasterxml/aalto/out/WriterConfig.java

./src/main/java/com/fasterxml/aalto/util/CharsetNames.java
./src/main/java/com/fasterxml/aalto/util/DataUtil.java
./src/main/java/com/fasterxml/aalto/util/EmptyIterator.java
./src/main/java/com/fasterxml/aalto/util/IllegalCharHandler.java
./src/main/java/com/fasterxml/aalto/util/SingletonIterator.java
./src/main/java/com/fasterxml/aalto/util/TextAccumulator.java
./src/main/java/com/fasterxml/aalto/util/TextBuilder.java
./src/main/java/com/fasterxml/aalto/util/TextUtil.java
./src/main/java/com/fasterxml/aalto/util/UriCanonicalizer.java
./src/main/java/com/fasterxml/aalto/util/XmlConsts.java

./src/main/java/test/BasePerfTest.java
./src/main/java/test/RunStreamWriter.java
./src/main/java/test/TestAsyncReader.java
./src/main/java/test/TestBase64Reader.java
./src/main/java/test/TestEventReader.java
./src/main/java/test/TestLineReader.java
./src/main/java/test/TestNameHashing.java
./src/main/java/test/TestNameTable.java
./src/main/java/test/TestPNamePerf.java
./src/main/java/test/TestRawStream.java
./src/main/java/test/TestSaxReader.java
./src/main/java/test/TestScannerPerf.java
./src/main/java/test/TestStreamCopier.java
./src/main/java/test/TestStreamReader.java
./src/main/java/test/TestTypedSpeed.java
./src/main/java/test/TestUTF8.java

./src/test/java/async/AsyncReaderWrapperForByteArray.java
./src/test/java/async/AsyncReaderWrapperForByteBuffer.java
./src/test/java/async/AsyncTestBase.java
./src/test/java/async/TestAsyncViaEventReader.java
./src/test/java/async/TestCDataParsing.java
./src/test/java/async/TestCharactersParsing.java
./src/test/java/async/TestCommentParsing.java
./src/test/java/async/TestDoctypeParsing.java
./src/test/java/async/TestElementParsing.java
./src/test/java/async/TestEntityParsing.java
./src/test/java/async/TestPIParsing.java
./src/test/java/async/TestSurrogates.java
./src/test/java/async/TestXmlDeclaration.java

./src/test/java/base/BaseTestCase.java

./src/test/java/evt/TestLaziness.java

./src/test/java/sax/TestEntityResolver.java
./src/test/java/sax/TestSaxReader.java

./src/test/java/stream/TestDTDSkimming.java
./src/test/java/stream/TestNameDecoding.java
./src/test/java/stream/TestSimple.java
./src/test/java/stream/TestSurrogates.java

./src/test/java/util/TestPNameTable.java
./src/test/java/util/TestTextAccumulator.java

./src/test/java/wstream/TestIndentation.java
./src/test/java/wstream/TestLongerContent.java
./src/test/java/wstream/TestNameEncoding.java

Please, confirm the licensing of code and/or content/s, and add license headers.

https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Clarification

Thanks in advance
Regards

**Comment by cowtowncoder** [comment]
The whole project is under Apache License 2.
