### ISSUE TITLE
Re-feeding parser after EVENT_INCOMPLETE results in exception upon reading next event type

### ISSUE THREAD

**Issue by shvalb** [FasterXML/aalto-xml#39]
Hi,

The flow is pretty basic.
1. Parse first xml file --> Results in EVENT_INCOMPLETE.
2. Parse 2nd file --> Causes exception upon getting next event type.

Using aalto-xml version 1.0.0

Attached reproduction zip file (Eclipse Neon).

Thank you!
[reproduction_env.zip](https://github.com/FasterXML/aalto-xml/files/392673/reproduction_env.zip)

**Comment by cowtowncoder** [comment]
Looking at code it seems like you are trying to feed 2 documents with same parser. This is not supposed to work as content is invalid -- valid XML content includes exactly one (root) element, and not two. Similarly it is illegal to encounter second xml declaration.

To process multiple documents you need separate parsers: parsers are not designed as reusable and there is no real benefit from attempting that.
