### ISSUE TITLE
Unicode: surrogate pairs encoded invalidly after x number of chars

### ISSUE THREAD

**Issue by JervenBolleman** [FasterXML/aalto-xml#45]
The problem here is that the character Kappa starts being encoded as xml entities, unfortunately this is an non valid character encoding. I don't understand why this is happening and why it happens after X characters instead of at any point.

```
@Test
public void tooManyKappas()
	 throws XMLStreamException
{
	XMLOutputFactory factory = OutputFactoryImpl.newInstance();
	if (factory instanceof OutputFactoryImpl) {
	     ((OutputFactoryImpl) factory).configureForSpeed();
        }
        //loop to find exactly at which point entity encoding kicks in.
	for (int j = 0; j < 1000; j++) {
		final ByteArrayOutputStream baos = new ByteArrayOutputStream();
		XMLStreamWriter writer = factory.createXMLStreamWriter(baos, StandardCharsets.UTF_8.name());

		final String namespace = "http://example.org";

		StringBuilder kappas = new StringBuilder();

		for (int i = 0; i < (2000 + j); i++) {
			kappas.append("𝜅");
		}
		writer.writeStartElement("", "ex", namespace);
		writer.writeCharacters(kappas.toString());
		writer.writeEndElement();
		writer.close();

		assertEquals("fails at " + (2000 + j),
			    "<ex>" + kappas + "</ex>",
			    new String(baos.toByteArray(), StandardCharsets.UTF_8));
	}
}
```

I hope this minimized test case is off help. It's definitely due to something internal to aalto. WSTX does not have this issue (or at a much higher loop number...).

The problem really is that aalto-xml reader does not deal with its own output in this case. Which is correct as its the writer that is wrong.

**Comment by cowtowncoder** [comment]
Thank you for reporting this. Hoping to have a look now, before releasing 1.1.0.

As to why at certain point, I am guessing that entity happens to fall along output buffer boundary, getting handled from different codepath. These tend to be tricky ones to track down so it's good to have a reproduction.

**Comment by cowtowncoder** [comment]
Actually... let me see if I can reproduce. If it happens after certain number of loops, that does not really make as much sense.

**Comment by cowtowncoder** [comment]
Ok no. All that matters is the specific size, to get boundary alignment probably. So can just use the failing offset.

**Comment by cowtowncoder** [comment]
Turns out that code paths did vary between the cases, and code in split-boundary case was basically escaping all characters beyond 0x2000, including surrogate pairs. This should not be done, handling should be uniform.

Fixed for 1.1.0; thank you for reporting this!

**Comment by JervenBolleman** [comment]
Thank you so much for picking this up. It will be great to use aalto-xml again, it's a real speed boost! I really appreciate it that you took the time to look into this.

**Comment by cowtowncoder** [comment]
@JervenBolleman happy to fix it -- it has been a while as I am not that active with xml tools these days, but feels good to clean up the backlog. Aalto is not nearly as well tested as Woodstox is, but would be great to get it to same level of quality.
