### ISSUE TITLE
build.xml still refers to GPL

### ISSUE THREAD

**Issue by hyandell** [FasterXML/aalto-xml#51]
The build.xml refers to GPL. Given the project was relicensed in 2010, that's presumably old cruft.

**Comment by cowtowncoder** [comment]
Thanks, will remove. Definitely no trace of GPL should be left, past 0.5 or so (before I figured out exactly what to do wrt apache/lgpl).

**Comment by cowtowncoder** [comment]
Removed `build.xml`.
