### ISSUE TITLE
AsyncByteScanner.validPublicIdChar() incorrectly rejects digits

### ISSUE THREAD

**Issue by dmolesUC3** [FasterXML/aalto-xml#53]
The javadoc for `AsyncByteScanner.validPublicIdChar()` references [PubidLiteral](http://www.w3.org/TR/xml/#NT-PubidLiteral) in the XML 1.0 specification:

>     PubidLiteral ::= '"' PubidChar* '"' | "'" (PubidChar - "'")* "'"
>     PubidChar    ::= #x20 | #xD | #xA | [a-zA-Z0-9] | [-'()+,./:=?;!*#@$_%]

Note that this includes `[0-9]`. However, the [implementation of the method](https://github.com/FasterXML/aalto-xml/blob/2750fb4be212436ab2cdc5a4d11a0c04baa99451/src/main/java/com/fasterxml/aalto/async/AsyncByteScanner.java#L622-L645) does not:

```
    protected boolean validPublicIdChar(int c) {
        return
            c == 0xA ||                     //<LF>
            c == 0xD ||                     //<CR>
            c == 0x20 ||                    //<SPACE>
            (c >= '@' && c <= 'Z') ||       //@[A-Z]
            (c >= 'a' && c <= 'z') ||
            c == '!' ||
            (c >= 0x23 && c <= 0x25) ||     //#$%
            (c >= 0x27 && c <= 0x2F) ||     //'()*+,-./
            (c >= ':' && c <= ';') ||
            c == '=' ||
            c == '?' ||
            c == '_';
    }
```

Note also that [`com.fasterxml.aalto.util.XmlCharTypes.PUBID_CHARS`](https://github.com/FasterXML/aalto-xml/blob/2750fb4be212436ab2cdc5a4d11a0c04baa99451/src/main/java/com/fasterxml/aalto/util/XmlCharTypes.java#L106-L145) correctly includes these digits.

### Steps to reproduce:

1. Find or create a document matching the [Encoded Archival Description version 3](https://github.com/saa-ead-roundtable/ead3-toolkit) schema and containing the following `<!DOCTYPE>` declaration (e.g., add it to [this file](https://github.com/saa-ead-roundtable/ead3-toolkit/blob/master/ead3_single_level_minimum.xml)):

```xml
<!DOCTYPE ead PUBLIC "+// http://ead3.archivists.org/schema/ //DTD ead3 (Encoded Archival Description (EAD) Version 3)//EN" "ead3.dtd">
```

2. Attempt to parse it with an `AsyncXMLStreamReader`.

### Expected:

- File parses, or at any rate gets past the `<!DOCTYPE>` declaration.

### Actual:

- parsing fails with a `WFCException`:

```java
Error parsing XML stream
com.fasterxml.aalto.WFCException: Unexpected character '3' (code 51) in prolog (not valid in PUBLIC ID)
 at [row,col {unknown-source}]: [1,77]
	at com.fasterxml.aalto.in.XmlScanner.reportInputProblem(XmlScanner.java:1333)
	at com.fasterxml.aalto.in.XmlScanner.throwUnexpectedChar(XmlScanner.java:1498)
	at com.fasterxml.aalto.in.XmlScanner.reportPrologUnexpChar(XmlScanner.java:1358)
	at com.fasterxml.aalto.async.AsyncByteBufferScanner.parseDtdId(AsyncByteBufferScanner.java:1946)
	at com.fasterxml.aalto.async.AsyncByteBufferScanner.handleDTD(AsyncByteBufferScanner.java:1833)
	at com.fasterxml.aalto.async.AsyncByteBufferScanner.handlePrologDeclStart(AsyncByteBufferScanner.java:1264)
	at com.fasterxml.aalto.async.AsyncByteBufferScanner.nextFromProlog(AsyncByteBufferScanner.java:1067)
	at com.fasterxml.aalto.stax.StreamReaderImpl.next(StreamReaderImpl.java:790)
	at org.codehaus.stax2.ri.Stax2EventReaderImpl.nextEvent(Stax2EventReaderImpl.java:255)
```

**Comment by cowtowncoder** [comment]
Thank you for reporting this & contributing fix!
