### ISSUE TITLE
Support Latin-1 (ISO-8859-1) via Async parser

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/aalto-xml#59]
(note: sort of related to #50)

Up to 1.1.0, only UTF-8 and US-ASCII (7-bit Ascii) encodings are supported by async parser.
But since Latin-1 is Unicode value compatible with UTF-8 (even though differing in encoding details), it should be possible and relatively easy to allow that too.

**Comment by adamretter** [comment]
Thank you very much @cowtowncoder :-)

**Comment by adamretter** [comment]
@cowtowncoder Just wondering, did this make it into a release? I am trying version `1.1.0` and still seeing:

```
Unsupported encoding 'ISO-8859-1': only UTF-8 and US-ASCII support by async parser
 at [row,col {unknown-source}]: [1,42]
com.fasterxml.aalto.WFCException: Unsupported encoding 'ISO-8859-1': only UTF-8 and US-ASCII support by async parser
 at [row,col {unknown-source}]: [1,42]
	at com.fasterxml.aalto.in.XmlScanner.reportInputProblem(XmlScanner.java:1333)
	at com.fasterxml.aalto.async.AsyncByteScanner.verifyAndSetXmlEncoding(AsyncByteScanner.java:359)
```

**Comment by cowtowncoder** [comment]
Looks like it didn't; will be in `1.1.1`, which I hope I can get out soon. Life's bit hectic right now :)

**Comment by adamretter** [comment]
No worries. Thanks for letting me know :-). Best wishes @cowtowncoder

**Comment by cowtowncoder** [comment]
@adamretter Pushing 1.1.1 release out now with just this one fix, should be at MC in an hour.
