### ISSUE TITLE
Source bundles have no Bundle-SymbolicName in Manifest

### ISSUE THREAD

**Issue by trancexpress** [FasterXML/aalto-xml#61]
See e.g.:

http://jcenter.bintray.com/com/fasterxml/aalto-xml/1.0.0/
http://jcenter.bintray.com/com/fasterxml/aalto-xml/1.1.0/

E.g. from `aalto-xml-1.0.0-sources.jar`:

`
Manifest-Version: 1.0
Archiver-Version: Plexus Archiver
Created-By: Apache Maven
Built-By: tatu
Build-Jdk: 1.7.0_79
Specification-Title: aalto-xml
Specification-Version: 1.0.0
Specification-Vendor: FasterXML
Implementation-Title: aalto-xml
Implementation-Version: 1.0.0
Implementation-Vendor-Id: com.fasterxml
Implementation-Vendor: FasterXML
Implementation-Build-Date: 2015-11-23 19:35:01-0800
X-Compile-Source-JDK: 1.6
X-Compile-Target-JDK: 1.6
`

Same seems to apply for the stax2-api bundles, e.g. at:

http://jcenter.bintray.com/org/codehaus/woodstox/stax2-api/

Including the source bundles into an Eclipse product becomes difficult due to the missing symbolic names. Would be great if the names can be added, as done for the library bundles.

**Comment by trancexpress** [comment]
@cowtowncoder Some Eclipse plug-in development tools rely on symbolic bundle names, as this information is usually present in all available plug-ins.

Its not a huge problem, since its only the source bundles that miss the names.

**Comment by cowtowncoder** [comment]
@trancexpress Ok. As I said, if there's an easy way to add this information via Maven build, I'd be happy to add it. But I do not know of a way at this point.

**Comment by cowtowncoder** [comment]
Would need help with this, if it's still an issue. Closing since this 5+ years old.
