### ISSUE TITLE
Support disabling General Entity Reference replacement in attribute values

### ISSUE THREAD

**Issue by otcdlink-simpleuser** [FasterXML/aalto-xml#65]
With aalto-xml 1.1.0 disabling Entity Reference replacement causes an exception to be thrown in case of a non-standard Entity.

Using the test case of #64 with this line:

``` 
xmlInputFactory.setProperty( XMLInputFactory.IS_REPLACING_ENTITY_REFERENCES, false ) ;
```

We get the following exception:

```
com.fasterxml.aalto.WFCException: General entity reference (&en;) encountered in entity expanding mode: operation not (yet) implemented
 at [row,col {unknown-source}]: [1,18]

	at com.fasterxml.aalto.in.XmlScanner.reportInputProblem(XmlScanner.java:1333)
	at com.fasterxml.aalto.in.ReaderScanner.handleEntityInText(ReaderScanner.java:1256)
	at com.fasterxml.aalto.in.ReaderScanner.collectValue(ReaderScanner.java:899)
	at com.fasterxml.aalto.in.ReaderScanner.handleStartElement(ReaderScanner.java:794)
	at com.fasterxml.aalto.in.ReaderScanner.nextFromProlog(ReaderScanner.java:236)
	at com.fasterxml.aalto.stax.StreamReaderImpl.next(StreamReaderImpl.java:790)
	at com.otcdlink.chiron.wire.StaxPlayground.entityReplacement2(StaxPlayground.java:80)
```

**Comment by cowtowncoder** [comment]
XML specification requires DTD support to be handle general entity references, so as is Aalto can not really do this in standards-compliant way: it does not decode DTDs (although it may skip them relatively reliably), and thus can not detect invalid usage, and to skip ones that are declared (and error on undeclared).

But I guess it would be reasonable to allow quiet skipping by returning ENTITY_REFERENCE, if setting you mention is on.

**Comment by claudemamo** [comment]
Any news on this?

**Comment by cowtowncoder** [comment]
If there are news, there will update to the issue.

At this point I think a PR would be one way forward: I simply do not have time to add new features here.

**Comment by claudemamo** [comment]
PR opened: FasterXML/aalto-xml#74

**Comment by cowtowncoder** [comment]
@claudemamo thank you for suggesting a fix! Unfortunately there are couple of issues with it; I'll add notes on PR itself.

**Comment by cowtowncoder** [comment]
Merged, with just one significant change: `AaltoInputProperties.P_RETAIN_ATTRIBUTE_GENERAL_ENTITIES` is both the Stax AND SAX Feature name to use, instead of trying to reuse existing SAX feature (`http://xml.org/sax/features/external-general-entities`) -- latter has its own semantics and should not be reused in my opinion.

Also added a test so that new feature is usable with Stax API as well.

Will wait a bit before releasing 1.3.0, but planning to do that relatively soon.
