### ISSUE TITLE
'com.fasterxml.aalto.impl.StreamExceptionBase: Can not output XML declaration, after other output has already been done.' when trying to transform XML using XSLT

### ISSUE THREAD

**Issue by nestrada** [FasterXML/aalto-xml#7]
Hello,

I wanted to test out the performances of aalto so I wrote this simple test program where I indent some XML using an XSLT stylesheet and use StaXSources and StaXResults as the input and output of the Transformer respectively.

Here is my test code:

	public static void main(String[] args) throws Exception {

		SAXTransformerFactory xformerFactory = (SAXTransformerFactory) TransformerFactory
				.newInstance();

		InputStream is = null;

		is = XMLTest.class.getResourceAsStream("/xml/indenter.xsl");
		Templates indenter = xformerFactory.newTemplates(new StreamSource(is));
		is.close();

		System.out.println(indenter);

		File xml = new File(args[0]);
		File outXml = new File(args[0] + ".out");

		// XMLInputFactory xif = XMLInputFactory.newFactory(
		// "com.sun.xml.internal.stream.XMLInputFactoryImpl", XMLTest.class.getClassLoader());
		XMLInputFactory xif = XMLInputFactory.newFactory(
				"com.fasterxml.aalto.stax.InputFactoryImpl", XMLTest.class.getClassLoader());

		xif.setProperty(XMLInputFactory.IS_COALESCING, Boolean.TRUE);
		xif.setProperty(XMLInputFactory.IS_NAMESPACE_AWARE, Boolean.TRUE);
		System.out.println(xif);
		// XMLOutputFactory xof = XMLOutputFactory.newFactory(
		// "com.sun.xml.internal.stream.XMLOutputFactoryImpl", XMLTest.class.getClassLoader());
		XMLOutputFactory xof = XMLOutputFactory.newFactory(
				"com.fasterxml.aalto.stax.OutputFactoryImpl", XMLTest.class.getClassLoader());
		System.out.println(xof);

		Source in = new StAXSource(xif.createXMLStreamReader(new FileInputStream(xml)));
		Result out = new StAXResult(
				xof.createXMLStreamWriter(new FileOutputStream(outXml), "UTF-8"));

		indenter.newTransformer().transform(in, out);
		// xformerFactory.newTransformer().transform(in, out);

	}

And I get the exception visible in the title. Any help would be suggested.

Nicolas

**Comment by cowtowncoder** [comment]
Can not reproduce without an example.
