### ISSUE TITLE
Async parsing turns &quot; inside element content into apostrophe

### ISSUE THREAD

**Issue by jphelp32** [FasterXML/aalto-xml#78]
This issue does not occur in 1.2.2. It is present in 1.3.1. I'm told it's also present in 1.3.0, but I haven't confirmed that myself.

I think I can see the code that's doing this, and that it's been in place for a long time. Wondering if maybe other fixes in 1.3.x have caused this long-standing bug to surface where before it was hidden?

See:
* https://github.com/FasterXML/aalto-xml/blob/f5607db7b45d3d70ef2c5db15b1f6c2fe944b109/src/main/java/com/fasterxml/aalto/async/AsyncByteBufferScanner.java#L2401
* https://github.com/FasterXML/aalto-xml/blob/f5607db7b45d3d70ef2c5db15b1f6c2fe944b109/src/main/java/com/fasterxml/aalto/async/AsyncByteBufferScanner.java#L2957

Also two locations in `AsyncByteArrayScanner.java`

**Comment by jphelp32** [comment]
@cowtowncoder any thoughts on this? if accurate, it seems like a pretty severe issue. Could a fix be released in the near term?

**Comment by cowtowncoder** [comment]
@jphelp32 Yes, if someone provides a patch it could definitely be released. I do not have time to work on Aalto right now but can always help others with PRs.

**Comment by cowtowncoder** [comment]
Ok, I managed to find some time to work on this: fix itself is not a problem (trivial copy-paste problem) but just had to go and find a test to modify to verify goodness of fix for both input sources (byte array and `ByteBuffer` backed).

I'll release 1.3.2 soon, maybe today, with this fix. Thank you again for reporting the issue @jphelp32 !

**Comment by jphelp32** [comment]
Thanks @cowtowncoder !
