### ISSUE TITLE
` textAccumulator.addText(buf, start, end)` introduces security issue.

### ISSUE THREAD

**Issue by ChangXiaoning** [FasterXML/aalto-xml#85]
# Reproduce code

```
import com.fasterxml.aalto.util.*;

public static void main (String[] args) {
   textAccumulator = new TextAccumulator();
   char[] buf = new char[1840165617];
   textAccumulator.addText(buf, 0, buf.length);
}
```

# Output

```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:68)
	at java.lang.StringBuilder.<init>(StringBuilder.java:106)
	at com.fasterxml.aalto.util.TextAccumulator.addText(TextAccumulator.java:51)
	at TextAccumulatorTest.main(TextAccumulatorTest.java:31)
```

# Environment

jdk 1.8
aalto-xml 1.3.2

# Analysis

Our service invokes ` textAccumulator.addText(buf, start, end)`. However, if the user provides malicious `start` and `end`, making the variable `len` very large. When the program allocates heap for `this.mBuilder`, an OutOfMemoryError happens and our service crashes. `textAccumulator.addText()` should check user input `start` and `end`.

**Comment by cowtowncoder** [comment]
You should not expose `TextAccumulator` to end users -- it is not part of Aalto public API.
So it is only designed to be called by trusted; as such no boundary checks are made.
In fact, this class is not designed to even be used by application code but only by Aalto itself.

Aalto public API consists of Stax, Stax2 and SAX APIs.
